# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Sample

import flatbuffers

class IoTDevice(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsIoTDevice(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IoTDevice()
        x.Init(buf, n + offset)
        return x

    # IoTDevice
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IoTDevice
    def Pos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from .Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # IoTDevice
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return bytes()

    # IoTDevice
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Data import Data
            obj = Data()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # IoTDevice
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def IoTDeviceStart(builder): builder.StartObject(3)
def IoTDeviceAddPos(builder, pos): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(pos), 0)
def IoTDeviceAddName(builder, name): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def IoTDeviceAddData(builder, data): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)
def IoTDeviceStartDataVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def IoTDeviceEnd(builder): return builder.EndObject()
