#! /usr/bin/python
import time
import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), './python'))

import json
import flatbuffers
# Generated by `flatc`.
import IoTDevice.Sample.Data
import IoTDevice.Sample.Vec3
import IoTDevice.Sample.IoTDevice

from tcp_server import TCPServer

def main():
    s = TCPServer();
    s.start(9989)

    path = "./1.txt"

    while True :
        dict = {}
        data = []
        size = s.read(data, None)
        mydevice = IoTDevice.Sample.IoTDevice.IoTDevice.GetRootAsIoTDevice(data[0], 0)
        for i in xrange(mydevice.DataLength()):
            dict[mydevice.Data(i).Name()] = mydevice.Data(i).Value()
        json_val = json.dumps(dict)
        print "json_val = %s" % json_val
    
        f = open(path, 'w')
        f.write(json_val)
        f.write('\n')
        f.close()

    s.end()

if __name__ == '__main__':
    main()

